### ISSUE TITLE
About building shared libs.

### ISSUE THREAD

**Issue by ZhenshengLee** [continental/ecal#354] opened 2021-07-27 15:31 UTC
when running with rmw_ecal in ubuntu20.04 and ros2 foxy, the following runtime issue happens.

```sh
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: builtin_interfaces/msg/Duration.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
```

_Originally posted by @ZhenshengLee in https://github.com/continental/rmw_ecal/issues/19#issuecomment-870408015_

After google, I believe there is an issue about linking libprotobuf twice both from static and dynamic lib.

And I found that `libecal_pb` and `libecal_proto` are both static libs, which could be the reason of linking twice.

So, is an official method provided to build shared libs in CMakeLists.txt?

Or, should I manually edit the CMakeLists and change `ecal_add_library ` to `ecal_add_shared_library`?

Thanks. @FlorianReimold

**Comment by FlorianReimold** [comment] 2021-08-10 10:40
Linking twice against different protobuf version is something that cannot be done. Both libecal_pb and libecal_proto are static libraries that don't contain protobuf, but require the version that they are built against. If you are using a non-standard protobuf version on linux, you will have to compile eCAL yourself against that non-standard version.
If you are using eCAL on Windows, we ship protobuf with the eCAL installer and you should only use that version. But if you are using any other software that ships binary protobuf, you will have to compile one of those yourself to make sure both use the same protobuf version. This is important when using rmw_ecal on Windows, as ROS2 appears to ship another protobuf version as binary.

I hope this explanation helps you. If not, please elaborate what you are trying to achieve and what your issue is 👍

Regards
Florian

**Comment by ZhenshengLee** [comment] 2021-08-11 01:14
> Linking twice against different protobuf version is something that cannot be done. Both libecal_pb and libecal_proto are static libraries that don't contain protobuf, but require the version that they are built against. If you are using a non-standard protobuf version on linux, you will have to compile eCAL yourself against that non-standard version.
> If you are using eCAL on Windows, we ship protobuf with the eCAL installer and you should only use that version. But if you are using any other software that ships binary protobuf, you will have to compile one of those yourself to make sure both use the same protobuf version. This is important when using rmw_ecal on Windows, as ROS2 appears to ship another protobuf version as binary.
> 
> I hope this explanation helps you. If not, please elaborate what you are trying to achieve and what your issue is 
> 
> Regards
> Florian

Thanks you!

**Comment by Kerstin-Keller** [comment] 2021-08-11 12:37
Actually, the error that you encountered happens, when the same `.proto` files is compiled into two different `.dll` or `.so` files.
The proto file which causes the problem is not an ecal related proto File:
```builtin_interfaces/msg/Duration.proto```.
I do not know, if this protobuf file is internal to `ecal_rmw` or to `ROS`. @brakmic-aleksandar - do you know?

So the problem is definately not related to ecal, and how ecal links protobuf, because the questionable proto file is not part of eCAL. It could be related to `ecal_rmw` or whoever uses that protobuf file.

**Comment by brakmic-aleksandar** [comment] 2021-08-11 13:40
It's not an eCAL issue, that .proto file has been generated from ROS2 idl files, by protobuf typesupport.

**Comment by ZhenshengLee** [comment] 2021-08-11 13:45
> Actually, the error that you encountered happens, when the same `.proto` files is compiled into two different `.dll` or `.so` files.
> The proto file which causes the problem is not an ecal related proto File:
> `builtin_interfaces/msg/Duration.proto`.
> I do not know, if this protobuf file is internal to `ecal_rmw` or to `ROS`. @brakmic-aleksandar - do you know?
> 
> So the problem is definately not related to ecal, and how ecal links protobuf, because the questionable proto file is not part of eCAL. It could be related to `ecal_rmw` or whoever uses that protobuf file.

> It's not an eCAL issue, that .proto file has been generated from ROS2 idl files, by protobuf typesupport.

@brakmic-aleksandar is right, it's not an eCAL but an rmw_ecal_proto_cpp issue, which is tracked with https://github.com/continental/rmw_ecal/issues/19

The reason why I created the issue here is I thought building shared libs may be a workaroud way to solve this runtime crash.
Now I know it's not true.

Thanks.

**Comment by FlorianReimold** [comment] 2021-09-06 06:26
I am closing this in this main eCAL Repo, as it is an rmw_ecal issue.

**Closed by FlorianReimold** 2021-09-06 06:26 UTC
