### ISSUE TITLE
High CPU consumes when the topic with  low frequency, small message size 

### ISSUE THREAD

**Issue by long131ss** [continental/ecal#480] opened 2022-01-24 04:12 UTC
**Bug Description**
I just subscribed to one topic /scam, the frequency is 10hz， message size is 3k.

```
  void OnReceive(const char* topic_name_, const struct eCAL::SReceiveCallbackData* data_)
  {
    std::cout << "OnReceive scam message size(KB):"<< (data_->size)/1024 << std::endl;
  }

int main(int argc, char **argv) {
  // Initialize eCAL
    eCAL::Initialize(argc, argv, "listener");
    eCAL::CSubscriber sub("/scam");
    sub.AddReceiveCallback(std::bind(OnReceive, std::placeholders::_1, std::placeholders::_2));
    while (eCAL::Ok()) {
      // sleep 100 ms
      std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
}
```
I found the CPU ratio is relatively high as bellow:
![Selection_187](https://user-images.githubusercontent.com/7857437/150720610-3a11b3b6-b06a-469e-bd83-a5d79a24aab6.png)

**Expected behavior**
As a comparison, I also tested another framework zero-zmq , the CPU usage is below 1%;

**Test Env**
 - OS: Ubuntu 16.04
 - Platform
 Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    3
Socket(s):             2
CPU max MHz:           1800.0000
CPU min MHz:           408.0000

**Comment by rex-schilasky** [comment] 2022-01-24 13:29
Hi @long131ss,

thank you for sharing this issue and for your effort. Two more questions to reproduce it optimally. What eCAL version do you use ? If it is a released version .. would it be possible to check the current master too ?
Besides the topic that is consumed by your applications are there other topics that are flying around in your network ? I ask because there are 2 layers that can consume CPU load inside an eCAL application. The one that is handling data transfer and another one doing the registration/monitoring handling in the background. I try to figure out which one to optimize :-)

Best, ReX

**Comment by long131ss** [comment] 2022-01-25 04:42
Hi,@rex-schilasky, Thanks very much for your reply. 
Answer to your question, I am working on the latest master version, the latest commit id is 3a1050b.
Yes, because I have integrated the eCal framework into our robotic system, there are other topics in my system.

I use google CPU evaluation tool gperftools , to try to figure out which function or module consumes the cpu . I can show you the result as below, It seems that eCAL CThread HelperThread comsumes most of the cpu.
[prof.pdf](https://github.com/continental/ecal/files/7930627/prof.pdf)

Best regards. Jack

**Comment by rex-schilasky** [comment] 2022-01-25 08:47
Hi @long131ss,

great analysis, thank you. The `CThread::HelperThread` is a common thread helper function (as the name says) used to create threads for different core functionalities. One of these functions is to collect information from the registration layer and collect them in you eCAL node (matching pub/sub, other services, topic names and types and so on). This registration logic is triggered from every process in a fixed refresh time. This time can be configured in the global configuration ecal.ini file.
You can increase this refresh time to decrease the overall CPU usage for that functionality. The only disadvantage is that the monitoring refresh rate gets lower and that your pub/sub will need more time to connect. Currently this time is set to 1000 ms.

Can you please give it a try and increase the `registration_refresh` parameter and check again ?

```ini
; --------------------------------------------------
; COMMON SETTINGS
; --------------------------------------------------
; registration_timeout    = 60000                   Timeout for topic registration in ms (internal)
; registration_refresh    = 1000                    Topic registration refresh cylce (has to be smaller then registration timeout !)
; --------------------------------------------------
[common]
registration_timeout      = 60000
registration_refresh      = 1000                <<<<<  maybe 2500 ??
```

Another question .. how many other entities (publisher/subscriber) are active in your eCAL network when doing this profiling ?

Best, ReX

PS: I checked your code sample on my standard i5 machine and the CPU load is between 0.0 and 0.1 even I run about 200 publisher in other nodes ..

**Comment by rex-schilasky** [comment] 2022-01-25 09:37
One more reply :-).

The udp sample receiver used for udp user payload and udp registration payload is currently timeouting with 10 ms on the specific sockets. This timeout is set [here](https://github.com/continental/ecal/blob/e2619cb44b0157dc68f1f3cec73396e39961c061/ecal/core/src/io/rcv_sample.cpp#L235).

Can you please adapt this function call

```cpp
  // wait for any incoming message
  size_t recv_len = sample_receiver_->Receive(m_msg_buffer.data(), m_msg_buffer.size(), 10);
```

to

```cpp
  // wait for any incoming message (100 ms timeout now)
  size_t recv_len = sample_receiver_->Receive(m_msg_buffer.data(), m_msg_buffer.size(), 100);
```
Would be interesting if that matters on your platform. This change would not decrease any performance but relaxing the udp receive thread logic to run less (empty) cycles.

Best, ReX

**Comment by rex-schilasky** [comment] 2022-01-25 14:18
Can you please give increase the mentioned `registration_refresh` parameter and check again ?

**Comment by long131ss** [comment] 2022-01-25 14:29
sorry，i forgot  to  tell you that  i  increased the registration_refresh to 2500 in ecal.ini .

**Comment by FlorianReimold** [comment] 2022-02-15 09:00
Can we close this issue? Is the question solved?

**Comment by rex-schilasky** [comment] 2022-02-15 09:02
Unfortunately no "solution" here. I rerun the profiler and could not find real potential for improvement here. So for now we can close this.

**Closed** 2022-02-18 12:21 UTC
Labels: question

**Comment by Kerstin-Keller** [comment] 2022-02-21 09:17
@rex-schilasky have you profiled on windows or linux? I guess most code is identical but it does differ in some places.
