### ISSUE TITLE
Python3 application crashes in eCAL thread start.

### ISSUE THREAD

**Issue by lz129** [continental/ecal#133] opened 2020-12-02 14:46 UTC
I'm currently working on a simple bidirectional gateway between eCAL and WAMP using the Crossbar / Autobahn twisted library for Python. 

Version: 
eCAL v5.7.4 (03.11.2020)

The application terminates in roughly 50% with 
```
terminate called without an active exception
Aborted (core dumped)
```
The error happens during initialization before any incoming eCAL messages. When the initialization succeeds the application continues running stable.

Source code: (without interface files, pls. ask for details)
[ecal_bridge.py.tar.gz](https://github.com/continental/ecal/files/5629963/ecal_bridge.py.tar.gz)

The call stack retrieved with gdb is as follows:
```
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fde5fae8921 in __GI_abort () at abort.c:79
#2  0x00007fde5a3e6957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fde5a3ecae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fde5a3ecb21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fde5ac4821c in eCAL::CThread::Start(int, std::function<int ()>) () from /usr/lib/libecal_core.so.5
#6  0x00007fde5abf6443 in eCAL::CMulticastLayer::AddSubscription(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, eCAL::QOS::SReaderQOS) () from /usr/lib/libecal_core.so.5
#7  0x00007fde5abf266a in eCAL::CDataReader::StartDataLayers() () from /usr/lib/libecal_core.so.5
#8  0x00007fde5abf4615 in eCAL::CDataReader::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libecal_core.so.5
#9  0x00007fde5abeac1a in eCAL::CSubscriber::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libecal_core.so.5
#10 0x00007fde5ac2a33f in sub_create(char const*, char const*) () from /usr/lib/libecal_core.so.5
#11 0x00007fde5b55d41c in sub_create(_object*, _object*) () from /usr/local/lib/python3.6/dist-packages/ecal-5.7.3-bionic-py3.6.egg/ecal/_ecal_core_py.so
#12 0x000000000050a12f in ?? ()
#13 0x000000000050beb4 in _PyEval_EvalFrameDefault ()
#14 0x00000000005095c8 in ?? ()
#15 0x000000000050a2fd in ?? ()
#16 0x000000000050beb4 in _PyEval_EvalFrameDefault ()
#17 0x0000000000507be4 in ?? ()
... (more Python stack frames)
```

**Comment by FlorianReimold** [comment] 2020-12-04 08:43
From looking at the gdb stack I cannot tell you why this crashed. Can you provide a minimal example that I can execute on my machine?

**Comment by lz129** [comment] 2020-12-04 10:20
Hello Florian,
thank you for the first look at the issue. It could take a day or two to strip down the program to the bare minimum showing the issue. I'll get back to you when it's done.

Best regards,
Josef

You may also contact me via:

Josef Baumgartner
Holistic Engineering and Technologies (he[a]t)
A HEAT RAE AT SW CT eH
E-Mail:    josef.baumgartner@continental.com

**Comment by FlorianReimold** [comment] 2021-01-12 07:46
Does the issue still exist or can we close this issue?

**Comment by lz129** [comment] 2021-01-21 08:09
Hello Florian,
the issue still exist but is not critical. The error occurs only on startup in some cases. When the application runs then everything is stable. The application is executed in a docker container environment and the restart option in docker-compose handles a startup crash.
Nevertheless I try to strip down the app and provide you this source code. The issue can be currently regarded a low priority.

--josef

**Comment by rex-schilasky** [comment] 2021-03-30 10:50
@lz129: If you can reproduce that issue with a minimal sample, I will reopen that issue, for now I will close it because we can not reproduce it unfortunately.

**Closed by rex-schilasky** 2021-03-30 10:50 UTC
