### ISSUE TITLE
eCAL vcpkg

### ISSUE THREAD

**Issue by niclar** [continental/ecal#359] opened 2021-08-11 15:20 UTC
Hi, would you consider adding a vcpkg build (for the ecal libraries not the gui & thirdparty libraries) ? -That would greatly ease the build and integration process on windows & linux.

**Comment by Kerstin-Keller** [comment] 2021-08-12 14:45
Hi @niclar,

in general we're not opposed to adding eCAL to any dependency manager.
However, we do not have any experience with vcpkg whatsoever, and it's not so much in our scope.
We're happy to give guidance accept contributions for adding eCAL to vcpkg.

Does it require our repo to have any packaging files, or is there a central repository with recipes?
In general, our build is based purely on CMake and highly configurable, such that it's possible to consume external dependencies and build the sdk only.

**Comment by niclar** [comment] 2021-08-16 13:28
Hi, it's a central repository with recipes and based on cmake. 

I'm trying to create a ecal port but I run in to the same ecal cmake recursion issue as reported here;

https://github.com/microsoft/vcpkg/issues/11307


With portfile.cmake like;

`vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO continental/ecal
    REF 88d77f278f5e8f3dcb9b4443e3a4e2bc9a3cf5ce #eCAL v5.9.0
	SHA512 a483568b16ae191410d7a8cd8bfba59570be2a2f912f3fa9718fe74a4a5f3de910bed5831781e38617924da69c1cc625836df2e507a9ef7dea04e03c597de8fe
    HEAD_REF master)

vcpkg_configure_cmake(
	SOURCE_PATH ${SOURCE_PATH}
	OPTIONS
	    -DCMAKE_MAXIMUM_RECURSION_DEPTH=3000
		-D_WIN32_WINNT=0x0A00
		-DHAS_QT5=OFF
		-DBUILD_SAMPLES=OFF
		-DECAL_INSTALL_SAMPLE_SOURCES=OFF 
		-DECAL_THIRDPARTY_BUILD_SPDLOG=OFF 
		-DECAL_THIRDPARTY_BUILD_TINYXML2=OFF
		-DECAL_THIRDPARTY_BUILD_FINEFTP=OFF
		-DECAL_THIRDPARTY_BUILD_TERMCOLOR=OFF
		-DECAL_THIRDPARTY_BUILD_PROTOBUF=OFF
		-DECAL_THIRDPARTY_BUILD_CURL=OFF
		-DECAL_THIRDPARTY_BUILD_HDF5=OFF
		-DECAL_LINK_HDF5_SHARED=OFF
		-DCPACK_PACK_WITH_INNOSETUP=OFF
	PREFER_NINJA)

vcpkg_install_cmake()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/lib/cmake)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib/cmake)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/bin)

file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
`

**Comment by Kerstin-Keller** [comment] 2021-08-17 07:09
I suspect that the problem is in the following lines of code:

https://github.com/continental/ecal/blob/a8d04cb408e0bc6918b07026db0d31ffc5f7d5aa/CMakeLists.txt#L351-L355

We're using a pattern here described by Daniel Pfeifers talk at [CppNow](https://github.com/boostcon/cppnow_presentations_2017/blob/master/05-19-2017_friday/effective_cmake__daniel_pfeifer__cppnow_05-19-2017.pdf) (slide 34), where `find_package` is redefined, to be called only when a given package is **NOT** included as a submodule and build with the rest of eCAL.
It's a pattern that works very well, but breaks, if anyone else is also redefining the same function, which vcpkg seems to do.

What we can do is to make an option for the redefinition, or guard it somehow, but then still the build will fail, at least for `CMakeFunctions`. Should we make a branch to experiment there?

**Comment by niclar** [comment] 2021-08-17 07:59
Thanks @Kerstin-Keller. Yes I'll make it optional and see how far it gets me. 

Vcpkg can patch the build / cmakes so there's no need for a branch just yet. 

Besides this recursion error there are some thirdparty dependencies (tclap, simpleini) that don't resolve cleanly but these are probably best fixed in vcpkg.

**Comment by Kerstin-Keller** [comment] 2021-08-17 09:11
Ok, thanks. Let me know if you encounter any other problems.
Tclap and simpleini are tricky, since they don't officially provide any CMake find packages.
Hence eCAL provides some itself, they are stored here:
https://github.com/continental/ecal/tree/master/cmake/Modules

**Comment by niclar** [comment] 2021-08-30 14:28
FYI filed a PR https://github.com/microsoft/vcpkg/pull/19802 just now (mvp builds & runs in windows & linux)
-feel free to integrate the patches or variants of them in ecal.

**Comment by Kerstin-Keller** [comment] 2021-08-31 09:17
Thanks @niclar for moving this foward. I will take a look at the necessary changes and what we can incorporate into the repository!

**Comment by niclar** [comment] 2021-09-02 08:47
@Kerstin-Keller can you have a look at https://github.com/microsoft/vcpkg/pull/19802 how do you want to handle the static build? It seems to me dependencies are incorrectly dynamically linked, no ?

**Comment by KerstinKeller** [comment] 2021-09-02 14:25
Hi @niclar,
as of now, we have disabled static builds for eCAL in general, to a) reduce transitive dependencies (as you know, eCAL, even the core, has quite a lot of dependencies - and if we link them statically, we don't need to distribute them with eCAL).
The other point is that linking ecal twice (e.g. static linkage into an application and dll at the same time can lead to serious trouble). 
And then we also have the eCAL Time Plugins. You can disable them, as strictly speaking, for the average use-case, they are not required.

Are static builds a requirement for vcpackage? I will take a look at the issue, and comment there, too.

**Comment by Kerstin-Keller** [comment] 2021-09-02 14:31
Hi @niclar,
as of now, we have disabled static builds for eCAL in general, to a) reduce transitive dependencies (as you know, eCAL, even the core, has quite a lot of dependencies - and if we link them statically, we don't need to distribute them with eCAL).
The other point is that linking ecal twice (e.g. static linkage into an application and dll at the same time can lead to serious trouble).
And then we also have the eCAL Time Plugins. You can disable them, as strictly speaking, for the average use-case, they are not required.

Are static builds a requirement for vcpackage? I will take a look at the issue, and comment there, too.

**Comment by niclar** [comment] 2021-09-02 15:13
a static build is a requirement for us if nothing else.   

"linking ecal twice", just remove the dynamic dependencies for the static build , make it restricted if needed and all is well defined and good.

**Comment by Kerstin-Keller** [comment] 2021-09-02 15:36
In general, you might find some problems when consuming eCAL then, considering `eCALConfig.cmake`. Some dependencies are header only (asio, simpleini, so they won't be a problem), but I am not 100% sure if it applies to to all the dependencies.

**Comment by niclar** [comment] 2021-09-03 07:45
The static dependencies required for a static ecal core is 
    "pthread",
    "asio",
    "tclap",
    "simpleini",
    "hdf5",
    "protobuf"


That build works & runs just fine and would constitute a mvp static build.

That was what I originally pushed.

**Comment by FlorianReimold** [comment] 2022-03-04 09:24
The discussion seems to be inactive. Can we close this issue?

**Closed** 2022-03-08 11:42 UTC
