### ISSUE TITLE
Service call request limit?

### ISSUE THREAD

**Issue by bsirang** [continental/ecal#581] opened 2022-03-28 15:31 UTC
**Describe the bug**
I am running into an issue where a service call fails seemingly because the request proto message size is too large. I am using a proto with a repeated field, and I am sending a long list.

I didn't yet narrow down exactly what the threshold for message size is.

**To Reproduce**
1. Create a service with a request message that has a repeated list
2. Create a large request message, and issue the service call
3. Observe that the service fails to process the call

**Expected behavior**
The service call succeeds

**Additional context**
I looked through ecal.ini and didn't see any buffer sizes that may be related to service calls. So primarily, I'd just like to know if there is some kind of buffer limit somewhere, and how one could change it. Maybe this is something that should be make available in ecal.ini?

**Comment by bsirang** [comment] 2022-03-30 21:43
@rex-schilasky any initial thoughts on this? Thanks!

**Comment by rex-schilasky** [comment] 2022-03-31 06:31
@bsirang can you give me a rough estimation for the size limit ? I did not check in detail but a problematic candidate could be the `max_length` here https://github.com/continental/ecal/blob/7931b8dda3dc8ad7c424d66ac8dfe55c7a6d9e36/ecal/core/src/service/asio_server.h#L174.

**Comment by bsirang** [comment] 2022-03-31 23:37
@rex-schilasky That could be it... I just did a larger (but feasible) test request and measured that it was over 100kB.

However, I skimmed the code and see that there is logic to keep reading until there's nothing left to read on the socket: https://github.com/continental/ecal/blob/7931b8dda3dc8ad7c424d66ac8dfe55c7a6d9e36/ecal/core/src/service/asio_server.h#L84

So at a glance it doesn't seem like that max_length is limiting the size of the request (at least not intentionally).

**Comment by rex-schilasky** [comment] 2022-04-01 09:07
I will setup a test and try to reproduce that.

**Comment by rex-schilasky** [comment] 2022-04-22 11:05
@bsirang I tried to reproduce that issue, but I can't. Do your services run on the same host ? I created a gtest (in one c++ unit) and this is running correctly even with very large messages.

**Comment by bsirang** [comment] 2022-04-25 19:08
Oh interesting... Thanks for attempting to reproduce.

Yes our services were on the same host. Do eCAL services run on top of a TCP socket always? Or is there also some kind of shared memory transport? We do run our applications in docker containers though, but I am using various `docker run` flags that should be giving the application direct access to host resources, so eCAL is using shared memory for pub/sub in this configuration

For now we have worked around the issue and are not sending large messages, so I don't have a super quick way to reproduce on my end again.

**Comment by FlorianReimold** [comment] 2022-04-26 06:45
eCAL Services always use TCP, as the performance is not as big of a concern as the reliability. So yes, maybe your Docker container is the issue here. What eCAL Version are you using anyways? Because we fixed Shared Memory in Docker containers [14 days ago](https://github.com/continental/ecal/commit/6ac9547f47ba8d0cf82001c1eb0d0e91c5342681) and the fix hasn't even been official released, yet. It will be part of eCAL 5.10.

**Comment by bsirang** [comment] 2022-04-26 16:12
I am using eCAL 5.9.5. Our service calls are generally working from one container to another, so I don't think Docker is the issue. We are running with --network=host so the TCP connections should have no problem.

We run our apps with these docker run flags, which allow the containers to use /dev/shm, use the same process ID namespace, and use the host's networking directly:
```
  --network host \
  --ipc host \
  --pid host \
  ```
  
Can you explain the nature of that shared memory fix a little bit more? I think using `--pid host` was the key in allowing eCAL to determine that the processes are on the same host even though they are in different containers.

**Comment by FlorianReimold** [comment] 2022-04-28 10:41
Yes, your parameters should make Network communication work with eCAL 5.9.5. But Shared Memory communication would not work as expected, as the hostid is different for each docker container. We removed the hostid check for eCAL 5.10 (figured that out while writing the [eCAL in Docker Documentation](https://continental.github.io/ecal/advanced/ecal_in_docker.html)).

Do you have some minimal example code that I can use to test it in a VM?

**Comment by bsirang** [comment] 2022-04-28 17:51
Oh interesting, I see the old logic looks at hostname. I should mention we've also been running with `-h "$(hostname)"` so that all the containers are using the same hostname. I do see a lot of `_shm` files under `/dev/shm` on the host system related to my pub/sub topic names, so it seems to be working.

**Comment by FlorianReimold** [comment] 2022-04-29 06:30
Not sure if you have somehow managed to create a working solution, but I assume that your tasks decide to not use SHM at all and fall back to UDP, as the hostid is different. Here is the old 5.9 code:
https://github.com/continental/ecal/blob/ea28ebe095a3381cb24cdf460dee29914b1205bd/ecal/core/src/ecal_reggate.cpp#L264

At least we couldn't get it working with a stock 5.9.5. You can call [sethostid](https://man7.org/linux/man-pages/man2/sethostid.2.html) and set the hostid manually in all docker containers but we didn't consider that a proper solution and removed the hostid check for eCAL 5.10.
Btw, you can easily check what layer each subscription is using by enabling the Layer column in eCAL Mon.

![image](https://user-images.githubusercontent.com/11774314/165894933-5cd07462-b4c1-49ea-9445-ca1033b7f08f.png)

However, all of this does have nothing to do with TCP Services 😉

**Comment by bsirang** [comment] 2022-05-04 00:24
Does the ecal_mon_cli also show the Layer information? I don't have a quick way of running ecal_mon_gui in the same docker environment.

However, on the host, if I do `ls -l /dev/shm` I do see stuff like this:
```
-rw-rw-rw- 1 foo  foo   4120 May  3 17:15 _topic_name_36240838_shm
-rw-rw-rw- 1 foo  foo   104 May  3 17:15 _topic_name_36240838_shm_10459_evt
-rw-rw-rw- 1 foo   foo    104 May  3 17:15 _topic_name_36240838_shm_10873_evt
-rw-rw-rw- 1 foo   foo    104 May  3 17:15 _topic_name_36240838_shm_11793_evt
-rw-rw-rw- 1 foo   foo    104 May  3 17:15 _topic_name_36240838_shm_mtx
```

Wouldn't that imply that shm is being used?

**Comment by rex-schilasky** [comment] 2022-05-04 06:32
Hi, the `ecal_mon_cli` does not show that information unfortunately. But maybe we could add that attribute here. With `ecal_mon --list` you can list all available topics and some basic information.
But there is a sample `ecal_sample_monitoring_rec` that is printing out everything,
I will open an issue and add the layer info to `ecal_mon_cli`.

**Comment by FlorianReimold** [comment] 2022-05-04 06:48
Honestly, it looks like your system is working. But obviously the sheer presence of a file does not conclude that somebody is reading it. Just saying. Are you running publisher and subscriber in the same docker container? With a natively installed eCAL 5.9.5 I get the following SHM files when running `ecal_sample_person_snd` and `ecal_sample_person_rec`.

```
-rw-rw-rw- 1 florian florian     96 Mai  4 08:30 ecal_shutdown_process_3560_evt
-rw-rw-rw- 1 florian florian     96 Mai  4 08:30 ecal_shutdown_process_3577_evt
-rw-rw-rw- 1 florian florian   4120 Mai  4 08:30 person_126463014_shm
-rw-rw-rw- 1 florian florian     96 Mai  4 08:30 person_126463014_shm_3577_evt   << Created when subscribing via SHM
-rw-rw-rw- 1 florian florian     96 Mai  4 08:30 person_126463014_shm_mtx
```

If working properly, you can also run eCAL Mon outside of your docker container, from another docker container or even on a different PC. Monitoring information are distributed via UDP and can be visualized by whatever eCAL Mon that can receive them.

**Comment by FlorianReimold** [comment] 2022-07-12 08:40
Hi @bsirang,

This GitHub issue seems to have changed scope from a potential Service Call Request Limit to Docker.
We were not able to reproduce the initial issue. Can you still reproduce it? Otherwise we may close this issue.

Regards
Florian

**Comment by bsirang** [comment] 2022-07-14 15:59
Hi @FlorianReimold, We haven't tried to reproduce it in a while since we have a workaround for our only large service call. Closing the issue sounds okay since you cannot reproduce. If I get more information on this in the future I will post it.

**Closed** 2022-07-18 07:18 UTC
Labels: in progress...
